// Справочник городов: id → [название, страна, код флага flag-icons, часовой пояс IANA].
// id хранится в настройках — не переименовывать существующие.
window.CITIES = {
  // Россия
  kaliningrad: ['Калининград', 'Россия', 'ru', 'Europe/Kaliningrad'],
  moscow: ['Москва', 'Россия', 'ru', 'Europe/Moscow'],
  spb: ['Санкт-Петербург', 'Россия', 'ru', 'Europe/Moscow'],
  kazan: ['Казань', 'Россия', 'ru', 'Europe/Moscow'],
  sochi: ['Сочи', 'Россия', 'ru', 'Europe/Moscow'],
  volgograd: ['Волгоград', 'Россия', 'ru', 'Europe/Volgograd'],
  samara: ['Самара', 'Россия', 'ru', 'Europe/Samara'],
  ufa: ['Уфа', 'Россия', 'ru', 'Asia/Yekaterinburg'],
  yekaterinburg: ['Екатеринбург', 'Россия', 'ru', 'Asia/Yekaterinburg'],
  chelyabinsk: ['Челябинск', 'Россия', 'ru', 'Asia/Yekaterinburg'],
  omsk: ['Омск', 'Россия', 'ru', 'Asia/Omsk'],
  novosibirsk: ['Новосибирск', 'Россия', 'ru', 'Asia/Novosibirsk'],
  krasnoyarsk: ['Красноярск', 'Россия', 'ru', 'Asia/Krasnoyarsk'],
  irkutsk: ['Иркутск', 'Россия', 'ru', 'Asia/Irkutsk'],
  yakutsk: ['Якутск', 'Россия', 'ru', 'Asia/Yakutsk'],
  vladivostok: ['Владивосток', 'Россия', 'ru', 'Asia/Vladivostok'],
  magadan: ['Магадан', 'Россия', 'ru', 'Asia/Magadan'],
  kamchatka: ['Петропавловск-Камчатский', 'Россия', 'ru', 'Asia/Kamchatka'],

  // Вьетнам и Юго-Восточная Азия
  hanoi: ['Ханой', 'Вьетнам', 'vn', 'Asia/Ho_Chi_Minh'],
  danang: ['Да Нанг', 'Вьетнам', 'vn', 'Asia/Ho_Chi_Minh'],
  hochiminh: ['Хошимин', 'Вьетнам', 'vn', 'Asia/Ho_Chi_Minh'],
  nhatrang: ['Нячанг', 'Вьетнам', 'vn', 'Asia/Ho_Chi_Minh'],
  phuquoc: ['Фукуок', 'Вьетнам', 'vn', 'Asia/Ho_Chi_Minh'],
  bangkok: ['Бангкок', 'Таиланд', 'th', 'Asia/Bangkok'],
  phuket: ['Пхукет', 'Таиланд', 'th', 'Asia/Bangkok'],
  pattaya: ['Паттайя', 'Таиланд', 'th', 'Asia/Bangkok'],
  phnompenh: ['Пномпень', 'Камбоджа', 'kh', 'Asia/Phnom_Penh'],
  vientiane: ['Вьентьян', 'Лаос', 'la', 'Asia/Vientiane'],
  kualalumpur: ['Куала-Лумпур', 'Малайзия', 'my', 'Asia/Kuala_Lumpur'],
  singapore: ['Сингапур', 'Сингапур', 'sg', 'Asia/Singapore'],
  jakarta: ['Джакарта', 'Индонезия', 'id', 'Asia/Jakarta'],
  bali: ['Бали', 'Индонезия', 'id', 'Asia/Makassar'],
  manila: ['Манила', 'Филиппины', 'ph', 'Asia/Manila'],

  // Восточная и Южная Азия
  beijing: ['Пекин', 'Китай', 'cn', 'Asia/Shanghai'],
  shanghai: ['Шанхай', 'Китай', 'cn', 'Asia/Shanghai'],
  guangzhou: ['Гуанчжоу', 'Китай', 'cn', 'Asia/Shanghai'],
  hongkong: ['Гонконг', 'Китай', 'hk', 'Asia/Hong_Kong'],
  taipei: ['Тайбэй', 'Тайвань', 'tw', 'Asia/Taipei'],
  seoul: ['Сеул', 'Южная Корея', 'kr', 'Asia/Seoul'],
  tokyo: ['Токио', 'Япония', 'jp', 'Asia/Tokyo'],
  ulaanbaatar: ['Улан-Батор', 'Монголия', 'mn', 'Asia/Ulaanbaatar'],
  delhi: ['Нью-Дели', 'Индия', 'in', 'Asia/Kolkata'],
  mumbai: ['Мумбаи', 'Индия', 'in', 'Asia/Kolkata'],
  goa: ['Гоа', 'Индия', 'in', 'Asia/Kolkata'],
  kathmandu: ['Катманду', 'Непал', 'np', 'Asia/Kathmandu'],
  colombo: ['Коломбо', 'Шри-Ланка', 'lk', 'Asia/Colombo'],
  male: ['Мале', 'Мальдивы', 'mv', 'Indian/Maldives'],

  // СНГ и Кавказ
  minsk: ['Минск', 'Беларусь', 'by', 'Europe/Minsk'],
  kyiv: ['Киев', 'Украина', 'ua', 'Europe/Kyiv'],
  chisinau: ['Кишинёв', 'Молдова', 'md', 'Europe/Chisinau'],
  tbilisi: ['Тбилиси', 'Грузия', 'ge', 'Asia/Tbilisi'],
  batumi: ['Батуми', 'Грузия', 'ge', 'Asia/Tbilisi'],
  yerevan: ['Ереван', 'Армения', 'am', 'Asia/Yerevan'],
  baku: ['Баку', 'Азербайджан', 'az', 'Asia/Baku'],
  almaty: ['Алматы', 'Казахстан', 'kz', 'Asia/Almaty'],
  astana: ['Астана', 'Казахстан', 'kz', 'Asia/Almaty'],
  tashkent: ['Ташкент', 'Узбекистан', 'uz', 'Asia/Tashkent'],
  samarkand: ['Самарканд', 'Узбекистан', 'uz', 'Asia/Samarkand'],
  bishkek: ['Бишкек', 'Киргизия', 'kg', 'Asia/Bishkek'],
  dushanbe: ['Душанбе', 'Таджикистан', 'tj', 'Asia/Dushanbe'],
  ashgabat: ['Ашхабад', 'Туркменистан', 'tm', 'Asia/Ashgabat'],

  // Ближний Восток
  istanbul: ['Стамбул', 'Турция', 'tr', 'Europe/Istanbul'],
  antalya: ['Анталья', 'Турция', 'tr', 'Europe/Istanbul'],
  dubai: ['Дубай', 'ОАЭ', 'ae', 'Asia/Dubai'],
  abudhabi: ['Абу-Даби', 'ОАЭ', 'ae', 'Asia/Dubai'],
  doha: ['Доха', 'Катар', 'qa', 'Asia/Qatar'],
  riyadh: ['Эр-Рияд', 'Саудовская Аравия', 'sa', 'Asia/Riyadh'],
  telaviv: ['Тель-Авив', 'Израиль', 'il', 'Asia/Jerusalem'],
  tehran: ['Тегеран', 'Иран', 'ir', 'Asia/Tehran'],
  cyprus: ['Лимасол', 'Кипр', 'cy', 'Asia/Nicosia'],

  // Европа
  london: ['Лондон', 'Великобритания', 'gb', 'Europe/London'],
  dublin: ['Дублин', 'Ирландия', 'ie', 'Europe/Dublin'],
  lisbon: ['Лиссабон', 'Португалия', 'pt', 'Europe/Lisbon'],
  madrid: ['Мадрид', 'Испания', 'es', 'Europe/Madrid'],
  barcelona: ['Барселона', 'Испания', 'es', 'Europe/Madrid'],
  paris: ['Париж', 'Франция', 'fr', 'Europe/Paris'],
  amsterdam: ['Амстердам', 'Нидерланды', 'nl', 'Europe/Amsterdam'],
  berlin: ['Берлин', 'Германия', 'de', 'Europe/Berlin'],
  zurich: ['Цюрих', 'Швейцария', 'ch', 'Europe/Zurich'],
  vienna: ['Вена', 'Австрия', 'at', 'Europe/Vienna'],
  rome: ['Рим', 'Италия', 'it', 'Europe/Rome'],
  prague: ['Прага', 'Чехия', 'cz', 'Europe/Prague'],
  warsaw: ['Варшава', 'Польша', 'pl', 'Europe/Warsaw'],
  budapest: ['Будапешт', 'Венгрия', 'hu', 'Europe/Budapest'],
  belgrade: ['Белград', 'Сербия', 'rs', 'Europe/Belgrade'],
  podgorica: ['Подгорица', 'Черногория', 'me', 'Europe/Podgorica'],
  athens: ['Афины', 'Греция', 'gr', 'Europe/Athens'],
  stockholm: ['Стокгольм', 'Швеция', 'se', 'Europe/Stockholm'],
  oslo: ['Осло', 'Норвегия', 'no', 'Europe/Oslo'],
  helsinki: ['Хельсинки', 'Финляндия', 'fi', 'Europe/Helsinki'],
  riga: ['Рига', 'Латвия', 'lv', 'Europe/Riga'],
  vilnius: ['Вильнюс', 'Литва', 'lt', 'Europe/Vilnius'],
  tallinn: ['Таллин', 'Эстония', 'ee', 'Europe/Tallinn'],

  // Африка
  cairo: ['Каир', 'Египет', 'eg', 'Africa/Cairo'],
  sharm: ['Шарм-эш-Шейх', 'Египет', 'eg', 'Africa/Cairo'],
  casablanca: ['Касабланка', 'Марокко', 'ma', 'Africa/Casablanca'],
  lagos: ['Лагос', 'Нигерия', 'ng', 'Africa/Lagos'],
  nairobi: ['Найроби', 'Кения', 'ke', 'Africa/Nairobi'],
  zanzibar: ['Занзибар', 'Танзания', 'tz', 'Africa/Dar_es_Salaam'],
  johannesburg: ['Йоханнесбург', 'ЮАР', 'za', 'Africa/Johannesburg'],
  capetown: ['Кейптаун', 'ЮАР', 'za', 'Africa/Johannesburg'],

  // Америка
  newyork: ['Нью-Йорк', 'США', 'us', 'America/New_York'],
  washington: ['Вашингтон', 'США', 'us', 'America/New_York'],
  miami: ['Майами', 'США', 'us', 'America/New_York'],
  chicago: ['Чикаго', 'США', 'us', 'America/Chicago'],
  denver: ['Денвер', 'США', 'us', 'America/Denver'],
  lasvegas: ['Лас-Вегас', 'США', 'us', 'America/Los_Angeles'],
  losangeles: ['Лос-Анджелес', 'США', 'us', 'America/Los_Angeles'],
  sanfrancisco: ['Сан-Франциско', 'США', 'us', 'America/Los_Angeles'],
  seattle: ['Сиэтл', 'США', 'us', 'America/Los_Angeles'],
  anchorage: ['Анкоридж', 'США', 'us', 'America/Anchorage'],
  honolulu: ['Гонолулу', 'США', 'us', 'Pacific/Honolulu'],
  toronto: ['Торонто', 'Канада', 'ca', 'America/Toronto'],
  vancouver: ['Ванкувер', 'Канада', 'ca', 'America/Vancouver'],
  mexico: ['Мехико', 'Мексика', 'mx', 'America/Mexico_City'],
  cancun: ['Канкун', 'Мексика', 'mx', 'America/Cancun'],
  havana: ['Гавана', 'Куба', 'cu', 'America/Havana'],
  bogota: ['Богота', 'Колумбия', 'co', 'America/Bogota'],
  lima: ['Лима', 'Перу', 'pe', 'America/Lima'],
  santiago: ['Сантьяго', 'Чили', 'cl', 'America/Santiago'],
  buenosaires: ['Буэнос-Айрес', 'Аргентина', 'ar', 'America/Argentina/Buenos_Aires'],
  saopaulo: ['Сан-Паулу', 'Бразилия', 'br', 'America/Sao_Paulo'],
  rio: ['Рио-де-Жанейро', 'Бразилия', 'br', 'America/Sao_Paulo'],

  // Океания
  perth: ['Перт', 'Австралия', 'au', 'Australia/Perth'],
  sydney: ['Сидней', 'Австралия', 'au', 'Australia/Sydney'],
  melbourne: ['Мельбурн', 'Австралия', 'au', 'Australia/Melbourne'],
  auckland: ['Окленд', 'Новая Зеландия', 'nz', 'Pacific/Auckland'],

  utc: ['UTC', 'Всемирное время', 'un', 'UTC'],
};

// Показываются в начале списка при пустом поиске
window.POPULAR_CITIES = ['moscow', 'kazan', 'danang', 'hanoi', 'bangkok', 'dubai', 'istanbul', 'london', 'newyork', 'tokyo'];
